### ISSUE TITLE
X86 gdb doesn't know about sigprot

### ISSUE THREAD

**Issue by arichardson** [CTSRD-CHERI/gdb#10]
When I open a coredump I get the following message:
```
Core was generated by `jls -j pgrep_j_test_1_1 -s'.
Program terminated with signal ?, Unknown signal.
```

**Comment by bsdjhb** [comment]
Native meaning a FreeBSD/mips gdb binary running on mips?  That is the one case that I think should work.  I think if you are cross-debugging it might not know about SIGPROT.  (There is an open GDB PR/patch submitted to GDB upstream this week to teach GDB about FreeBSD signal numbers when cross-debugging)

**Comment by arichardson** [comment]
Sorry by native I mean x86 debugging a MIPS binary.
