### ISSUE TITLE
Print capreg that caused the trap on SIGPROT

### ISSUE THREAD

**Issue by arichardson** [CTSRD-CHERI/gdb#20]
Would it be possible to print the register that caused the faul on SIGPROT?
I believe SIGPROT passes the capcause register as signal code
`ucode = cheri_capcause_to_sicode(trapframe->capcause);`

While the kernel prints a register dump just before but it would be nice if I didn't have to find the register in there. Furthermore, GDB could print the symbolic permissions which makes parsing this easier.

It would be nice to have something like the following printed by gdb
```
Program received signal SIGPROT, CHERI protection violation (length violation).
   caused by register $c22: 0x40795630 [rwRW,0x40795630-0x40795640]
0x00000000001533e4 in primary (n=OPERAND) at /exports/users/alr48/sources/cheribsd/bin/test/test.c:317
```

instead of the current output:
```
Program received signal SIGPROT, CHERI protection violation.
0x00000000001533e4 in primary (n=OPERAND) at /exports/users/alr48/sources/cheribsd/bin/test/test.c:317
```

**Comment by arichardson** [comment]
It seems like it always reports register zero for live processes:


```
BadInstr: 0x4807a062 invalid	$7,$20,$1
CHERI cause: ExcCode: 0x0a RegNum: $c07 (bounds cannot be represented precisely)

...

Program received signal SIGPROT, CHERI protection violation
Imprecise bounds fault caused by register c0: 0x0000000000000000 [,0x0-0xffffffffffffffff].
```

I added some debug output to the kernel and ksi_capreg is definitely being set: `SIGPROT ksi_capreg = 7`. So either it is being zeroed later in the kernel or GDB is not loading it correctly.

**Comment by bsdjhb** [comment]
You have to build gdb as a hybrid binary for this to work.  (Sorry for the delay, but I just relearned this myself.)
