### ISSUE TITLE
info locals/info args does not work for capabilities

### ISSUE THREAD

**Issue by arichardson** [CTSRD-CHERI/gdb#25]
I'm not sure if this is a bug in the debug info that clang is emitting or if it is gdb but if I use info locals (binary compiled at -O0) it only shows the integer values but not capabilities.
It always shows `foo = <error reading variable>`.

**Comment by arichardson** [comment]
Actually, I just noticed that this only affects the hybrid ABI and works fine in purecap. Therefore this is very low priority.

**Comment by bsdjhb** [comment]
Given that it's only in hybrid, this is almost certainly an issue with the debug info clang/llvm are generating and not something in GDB itself.
