### ISSUE TITLE
GDB-mips Assertion Fail

### ISSUE THREAD

**Issue by SamAinsworth** [CTSRD-CHERI/gdb#30]
From commit https://github.com/CTSRD-CHERI/gdb/commit/603d49fa7305344796fb47470c874deb7a793fe7 onwards,

I get the following issue whenever I try to run any binary under a non-pure capability setup (for example, gdb ls)

`/local/scratch/sa614/cheri/gdb/gdb/target.c:2170: internal-error: void target_mourn_inferior(ptid_t): Assertion 'ptid == inferior_ptid' failed.
A problem internal to GDB has been detected,
further debugging may prove unreliable.`

It works fine on the previous commit - https://github.com/CTSRD-CHERI/gdb/commit/3690ec413a4d3dc289396511f284d6ac19697c62

Presumably this is something to do with an incorrect assumption on the CHERI registers in non-pure mode?

**Comment by bsdjhb** [comment]
Yes, I get a different assertion usually with the number of registers being wrong.  Fixing it is non-trivial as it means having to GDB about pointer types with different sizes (it assumes all pointers for a given architecture have the same size).  This would also pave the way for supporting a __capability keyword in the C parser for GDB to be able to pretty-print capabilities when doing hybrid debugging.  I've kind of punted on fixing this as most of the time now for user debugging, purecap works well enough.  The kernel is one case that is going to be hybrid for some time though.

**Comment by st235** [comment]
hello everyone,
I am just wondering is there any progress on it?

**Comment by bsdjhb** [comment]
This should no longer be an issue in CHERI GDB 12.
