### ISSUE TITLE
GDB mips assertion error in mips_fbsd_supply_capregs()

### ISSUE THREAD

**Issue by qwattash** [CTSRD-CHERI/gdb#33]
Running gdb on qemu-mips when debugging an hybrid binary yields:
```
internal-error: void mips_fbsd_supply_capregs(struct regcache *, int, const void *, size_t, size_t): Assertion `register_size (gdbarch, mips_regnum (gdbarch)->cap_pcc) == regsize' failed.
```
HEAD to reproduce is at: 0356990d05

**Comment by bsdjhb** [comment]
MIPS is OBE, but the `cheri-12` branch has much better support for hybrid in general inherited from Morello GDB.
