### ISSUE TITLE
`show environment` is incorrect

### ISSUE THREAD

**Issue by arichardson** [CTSRD-CHERI/gdb#46]
```
# gdb --quiet --args env
Reading symbols from env...
(gdb) b exit
Breakpoint 1 at 0x3a00
(gdb) show environment
....
PATH=/opt/amd64/kde/bin:/usr/local/amd64/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin:/root/bin
....
(gdb) r
Starting program: /usr/bin/env
....
PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin:/root/bin
....

Breakpoint 1, exit (status=0) at /Users/alex/cheri/cheribsd/lib/libc/stdlib/exit.c:66
66      /Users/alex/cheri/cheribsd/lib/libc/stdlib/exit.c: No such file or directory.
(gdb) show environment
....
PATH=/opt/amd64/kde/bin:/usr/local/amd64/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin:/root/bin
....
SHELL=/bin/csh
...
(gdb) p getenv("PATH")
$1 = 0x7fffffffed8b "/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin:/root/bin"
```

Turns out csh reset PATH before starting env so my explicitly specified $PATH is ignored...

> Warning: On Unix systems, GDB runs your program using the shell indicated by your SHELL environment variable if it exists (or /bin/sh if not). If your SHELL variable names a shell that runs an initialization file when started non-interactively—such as .cshrc for C-shell, $.zshenv for the Z shell, or the file specified in the BASH_ENV environment variable for BASH—any variables you set in that file affect your program. You may wish to move setting of environment variables to files that are only run when you sign on, such as .login or .profile.

Workaround: `gdb -iex='set startup-with-shell off'`

**Comment by arichardson** [comment]
I guess it shows the environment prior to starting the process, but it would be much more useful to show the *current* environment.

**Comment by bsdjhb** [comment]
Ah, so that explains an issue I had with PATH also not being honored when running Apache's httpd.  gdb can only show the environment it passes to execve().  It can't retroactively change the environment in the grandchild when using startup-with-shell.  (And set environment is documented as such.)  Having a way to read the inferior's actual environment (info proc env) might be useful, but it would be a new feature upstream, not a CHERI-GDB specific fix.

**Comment by arichardson** [comment]
Yeah as a workaround `p @(char**)environ@20` works quite well.
