### ISSUE TITLE
gdb incorrect output on capability validity (array of capabilities)

### ISSUE THREAD

**Issue by drandynisbet** [CTSRD-CHERI/gdb#55]
Stupid question on  Morello/gdb ... on OpenJDK, we are inserting some symbol (pointers) into an array ... why does entry 1 in the array appear as both invalid and valid depending on how I print/access it
(gdb) print Symbol::_vm_symbols
$51 = {0x0, 0x4247c0f0 [rwRW,0x4247c000-0x424d6080] (invalid), 0x0 <repeats 997 times>}
(gdb) print Symbol::_vm_symbols[1]
$52 = (Symbol *) 0x4247c0f0 [rwRW,0x4247c000-0x424d6080]
(gdb) print Symbol::_vm_symbols[0]
$53 = (Symbol *) 0x0
and the array is declared as a static class member static Symbol* _vm_symbols[];
Have I missed a package update somewhere (llvm-morello is updated to the most recent), or is it an artefact of how gdb accesses/traverses the array of pointers?

**Comment by failys** [comment]
I get the same problem, which can be reproduced with the below:

```
#include <cassert>

int main(int argc, char **argv)
{  
  int * x[10] = {0};
  int * foo = new int(42);
  x[0] = foo;
  assert(*x[0] == *foo);
  delete foo; @
  return 0;
}
```
Like @drandynisbet , `p x[0]` indicates a valid capability, but `p x` indicates an invalid capability for the first element of the array.

**Comment by bsdjhb** [comment]
Thanks for the reproducer, and sorry for the delay in getting to it.  I've pushed a fix/workaround to the cheri-12 branch.  The issue had to do with GDB caching the memory bytes (but not tags) for an entire array and trying to print individual members by subsetting the larger byte array.  Normally this works as a more efficient form of caching to avoid hitting ptrace() for each array element.  However, the tag support in CHERI GDB is a bit limited in that each logical value can only store a single tag.  For values representing components like structs, unions, or arrays, GDB's value printers have to instead explicitly fetch capabilities when a component member is a capability.  This was missing for the array case which is what the committed change addresses.
