### ISSUE TITLE
Support for debugging sandboxes

### ISSUE THREAD

**Issue by arichardson** [CTSRD-CHERI/gdb#7]
Currently it is not easy to debug sandboxes since GDB doesn't know about the file mappings.

One solution might be adding support libcheri for `r_debug` to tell GDB about which files are loaded where.
However, I'm not sure that would work since the statically linked binaries don't have a DT_DEBUG/DT_MIPS_RLD_MAP

**Comment by bsdjhb** [comment]
This is OBE.  libcheri has been removed, and the current compartment support supplies this idea.
